### ISSUE TITLE
differentiate menu folders from other menu items

### ISSUE THREAD

**Issue by diemheych** [bxparks/rpn83p#20]
Is there room to add a small line above the folder menu items like on the HP-48 so you can easily tell it's a folder?

**Comment by bxparks** [comment]
It's funny, I've used HP calculators for... 30-35 years?... but I did not know what the heck this little menu line was until about 2-3 months ago.

I *think* there is a one-pixel row of extra space above those menu items, but I'm not sure. Needs to be researched. Also needs to be figured out how to draw that little line using the SDK.

Ideally, this is a small, self-contained feature that something that someone else could grab as a contributor. The HP-42S does not have this, and I don't recall seeing anyone complaining about the lack of this. Given the totally of all the other features that we could work on, how do we prioritize this? Obviously I have almost no need for this, because I every menu item like the back of my hand. But other *users* of RPN83P will find it helpful.

Anyway, I added back-link to this in https://github.com/bxparks/rpn83p/blob/develop/docs/FUTURE.md

**Comment by bxparks** [comment]
This turned out to be quite simple, after I figured out the appropriate OS calls. Here's what the menu looks like now:
![2024-04-16 menu folder icon](https://github.com/bxparks/rpn83p/assets/26933282/6596bd14-9316-4c6b-afdb-e86faddb2c33)

I have to update the screenshots in the documentation. There are currently 1346 screenshots, of which maybe 30-40% show the menus, so maybe 400-500 screenshots? It will take me days... I'm keeping this ticket open until the docs are updated.

**Comment by bxparks** [comment]
Fixed by v0.11.0
